### ISSUE TITLE
won't show docs :-(

### ISSUE THREAD

**Issue by marcelloh** [neilotoole/gohdoc#1]
As I moved everything to modules last week, I hoped that this would still show me my docs, even if my sources are outside of my gopath.

Would be nice if this worked, so I don't have to wait for modules to mature.

So, I've got this bundle of sources hidden om my computer, let 's say:
/data/somewhere/mystuff
if I start gohdoc .there, I expected the tool to grab all documentation from that starting point.

Bummer....

**Comment by neilotoole** [comment]
@marcelloh Apologies for not having responded to this sooner. Basically this modules problem lay with "godoc" itself, not gohdoc. See https://github.com/golang/go/issues/33655

As you'll see from that issue, godoc has recently been updated to support modules. If you install the latest version of godoc (`go get -u golang.org/x/tools/cmd/godoc`) things should start working again. Let me know if that works for you and I'll close the issue.

**Comment by marcelloh** [comment]
works!
