### ISSUE TITLE
Idea: scrape and save

### ISSUE THREAD

**Issue by marcelloh** [neilotoole/gohdoc#2]
I don't like the idea of a webserver that runs for nothing (unless we decide we kill it), so perhaps this is an idea:

What if you run the webserver, scrape the html and save that in a given directory, then kill the webserver, so we would have a generated browsable copy without running something that we might forget?

**Comment by neilotoole** [comment]
@marcelloh I agree that the running server feels a bit clunky. And it can lead to confusion, e.g. if you already have a godoc server running that's serving module `pkgX`, then running `gohdoc pkgY` in Y's dir will result in `Error: failed to find in server pkg list: pkgY`. I should improve that error message to at least advise to kill the other server.

However, I see two concerns with this idea:

* Performance: For large godoc repositories, esp when the stdlib is included, it could take some time to scrape all the pages. It's probably possible to overcome this by being intelligent about the order of pages to scrape (and perhaps to cache the stdlib scraped pages).
* Refresh: Currently if you're viewing the godoc for a package, and change the godoc for your code, refreshing the browser will show the updated godoc. If viewing static scraped HTML pages, we lose this functionality.

The refresh issue is the bigger concern for me. My current workflow, when working on a package, is that I run `gohdoc .` to view the godoc in the browser, and then I leave the browser window open. From time to time I'll return to that browser window and refresh, to view the latest godoc. I imagine that's a workflow that many people use.

Also, the loss of this refresh functionality means that godoc browser pages reached via gohdoc behave differently (no refresh) vs those reached directly via godoc, which seems like a bad path to start down.

**Comment by marcelloh** [comment]
Oh, but it doesn't have to be a replacement for the current innerworking.
Perhaps with an extra parameter, that we can do this?

**Comment by neilotoole** [comment]
@marcelloh well, it certainly could be done. However, without the server running, we lose other functionality.

* The godoc search box functionality will break.
* Some of the source viewing functionality will break.

For the latter, consider these URLs:

1. http://localhost:6060/src/fmt/print.go
2. http://localhost:6060/src/fmt/print.go?h=fmt.Println#L273
3. http://localhost:6060/src/fmt/print.go?s=820:1462#L35

The first link should continue to work, but 2 and 3 won't work as expected.

The scraped HTML would definitely be a second-class experience compared to the live HTML; some things, such as search, would be broken.

**Comment by marcelloh** [comment]
True :-)  just leave it as it is.
